version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "43000:3000"  # host:container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "45000:5173"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "45432:5432"  # dùng 45432 thay vì 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
