version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:5000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
