version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "43000:5173"  # host:container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "45000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12344321
      POSTGRES_DB: task_schedule
    ports:
      - "45432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
