version: "3.8"
services:
  nginx:
    build: ./nginx
    ports:
      - "45000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - task-network

  frontend:
    build: ./frontend
    expose:
      - "5173"
    depends_on:
      - backend
    networks:
      - task-network

  backend:
    build: ./backend
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - task-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12344321
      POSTGRES_DB: task_schedule
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  postgres_data:
